#!/usr/bin/env node
// Download the trained model + card data from S3, copy them into public/ under
// content-addressed names, and write public/model-manifest.json.
//
// Run by both `npm run fetch-assets` (local) and the deploy workflow, so CI and
// a laptop cannot produce different manifests. Requires the AWS CLI on PATH with
// credentials that can read the keys below (see README).
//
// Vite copies public/ verbatim -- no content hashing, unlike src/ imports -- so
// without the hashed names a redeploy reuses stable URLs and GitHub Pages'
// max-age=600 can hand a returning visitor last week's weights against this
// week's card map. That failure is silent: wrong predictions, no error.

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  existsSync, mkdirSync, readFileSync, rmSync, writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cacheDir = resolve(root, ".assets-cache");
const publicDir = resolve(root, "public");

const BUCKET = process.env.S3_BUCKET ?? "cr-games-bucket";
const REGION = process.env.AWS_REGION ?? "us-east-2";
const KEYS = {
  model:     process.env.MODEL_KEY          ?? "model-weights/model_int8.onnx",
  metadata:  process.env.MODEL_METADATA_KEY ?? "model-weights/model_int8.metadata.json",
  cardMap:   process.env.CARD_MAP_KEY       ?? "frontend-assets/card_to_token_id.json",
  imageUrls: process.env.PNG_URLS_KEY       ?? "frontend-assets/png_urls.json",
};

const LOCAL = {
  model:     resolve(cacheDir, "model_int8.onnx"),
  metadata:  resolve(cacheDir, "model_int8.metadata.json"),
  cardMap:   resolve(cacheDir, "card_to_token_id.json"),
  imageUrls: resolve(cacheDir, "png_urls.json"),
};

const offline = process.argv.includes("--offline");

/** Download one key. Throws unless `optional`, so a failed fetch fails the build
 *  rather than quietly producing a model-less deploy (vite build succeeds with
 *  an empty public/). */
const download = (key, dest, { optional = false } = {}) => {
  try {
    execFileSync("aws", ["s3", "cp", `s3://${BUCKET}/${key}`, dest, "--region", REGION],
      { stdio: "inherit" });
    return true;
  } catch {
    if (optional) {
      console.warn(`warning: optional object ${key} not downloaded`);
      return false;
    }
    throw new Error(
      `Failed to download s3://${BUCKET}/${key}\n` +
      `Check that the AWS CLI is installed and your credentials can read that key.`,
    );
  }
};

// --- 1. fetch -------------------------------------------------------------
mkdirSync(cacheDir, { recursive: true });
if (offline) {
  for (const [name, path] of Object.entries(LOCAL)) {
    if (name !== "metadata" && !existsSync(path)) {
      throw new Error(`--offline given but ${path} is missing. Run without --offline first.`);
    }
  }
  console.log("--offline: reusing .assets-cache/");
} else {
  download(KEYS.model, LOCAL.model);
  download(KEYS.cardMap, LOCAL.cardMap);
  download(KEYS.imageUrls, LOCAL.imageUrls);
  // Absent for any model trained before the sidecar was introduced; the app
  // degrades to vocabSize: null, which disables the out-of-range card filter.
  download(KEYS.metadata, LOCAL.metadata, { optional: true });
}

// --- 2. content-address into public/ --------------------------------------
// Wipe both directories first, so yesterday's hashed model and any un-hashed
// leftovers do not linger in the deploy. Everything in public/model/ and
// public/data/ is generated by this script -- put static assets elsewhere.
for (const dir of ["model", "data"]) {
  rmSync(resolve(publicDir, dir), { recursive: true, force: true });
  mkdirSync(resolve(publicDir, dir), { recursive: true });
}

const place = (src, dir, base, ext) => {
  const bytes = readFileSync(src);
  const digest = createHash("sha256").update(bytes).digest("hex");
  const name = `${base}-${digest.slice(0, 8)}${ext}`;
  writeFileSync(resolve(publicDir, dir, name), bytes);
  return { rel: `${dir}/${name}`, digest, bytes: bytes.length };
};

const model     = place(LOCAL.model,     "model", "model",            ".onnx");
const cardMap   = place(LOCAL.cardMap,   "data",  "card_to_token_id", ".json");
const imageUrls = place(LOCAL.imageUrls, "data",  "png_urls",         ".json");

// --- 3. metadata sidecar (optional) ---------------------------------------
let meta = {};
if (existsSync(LOCAL.metadata)) {
  meta = JSON.parse(readFileSync(LOCAL.metadata, "utf8"));
} else {
  console.warn("warning: no metadata sidecar; vocab_size filtering will be disabled.");
}

// --- 4. sanity check ------------------------------------------------------
// card_ids can hold a card that never appeared in an exported game, so the map
// is legitimately allowed to be larger than the embedding table. Feeding such a
// token reads past the Gather, which ORT's WASM backend does not catch -- the
// app filters them out, but a large count here means the dataset export dropped
// a lot of cards and the model is worse than it looks.
const cardIds = JSON.parse(readFileSync(LOCAL.cardMap, "utf8"));
const cardCount = Object.keys(cardIds).length;
if (meta.vocab_size != null) {
  const excluded = Object.entries(cardIds)
    .filter(([, id]) => id >= meta.vocab_size)
    .map(([name]) => name);
  if (excluded.length > 0) {
    console.warn(
      `warning: ${cardCount} cards in the map but vocab_size is ${meta.vocab_size}; ` +
      `${excluded.length} will be hidden: ${excluded.join(", ")}`,
    );
  }
}
const maxId = Math.max(...Object.values(cardIds));
if (maxId >= 200) {
  console.warn(
    `warning: highest card id is ${maxId}. Ids are cast to UInt8 during dataset ` +
    `export and 254 is INVALID_TOKEN -- this needs a wider dtype before 254.`,
  );
}

// --- 5. manifest ----------------------------------------------------------
// Paths are relative to import.meta.env.BASE_URL so one manifest works both at
// "/" locally and "/win_predictor_pipeline/" on Pages.
const manifest = {
  schemaVersion: 1,
  model: model.rel,
  modelSha256: model.digest,
  modelBytes: model.bytes,
  cardMap: cardMap.rel,
  imageUrls: imageUrls.rel,
  vocabSize: meta.vocab_size ?? null,
  modelConfig: meta.model_config ?? null,
  quantization: meta.quantization ?? null,
  trainedAt: meta.trained_at ?? null,
  trainingCommit: meta.training_commit ?? null,
  builtAt: new Date().toISOString(),
  buildCommit: process.env.BUILD_COMMIT ?? null,
};
writeFileSync(
  resolve(publicDir, "model-manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);

console.log(
  `manifest written: ${model.rel} ` +
  `(${(model.bytes / 1e6).toFixed(2)} MB, ${cardCount} cards, ` +
  `vocabSize=${manifest.vocabSize ?? "unknown"})`,
);
