[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jack", email = "jcm2022@icloud.com" }
]
requires-python = "==3.13.*"
dependencies = [
    "boto3>=1.43.78",
    "numpy>=2.5.2",
    "onnx>=1.20.0",
    "polars>=1.43.2",
    "prefect>=3.8.3",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "torch>=2.13.0",
    "wandb>=0.18.0",
    "common",
]

[project.scripts]
training = "training:main"

[tool.uv.sources]
common = { path = "../../libs/common", editable = true }

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
